changelog:
  exclude:
    labels:
      - no-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Improvements
      labels:
        - improvement
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
