version: 2

builds:
  - main: ./cmd/vault-plugin-secrets-honeycombio
    binary: vault-plugin-secrets-honeycombio
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_SHA256SUMS"
  algorithm: sha256

release:
  draft: true
